// Shim: export vx_* inline intrinsics as linkable symbols.
// vortex-lower-runtime-builtins generates `call @vx_core_id()` etc.,
// but in vx_intrinsics.h these are inline functions (CSR reads).
// This file provides non-inline definitions so the linker can resolve them.

#include <vx_intrinsics.h>

// Use wrapper names and alias them to the expected symbol names
int __attribute__((noinline)) __vx_core_id_wrapper(void) { return vx_core_id(); }
int __attribute__((noinline)) __vx_warp_id_wrapper(void) { return vx_warp_id(); }
int __attribute__((noinline)) __vx_thread_id_wrapper(void) { return vx_thread_id(); }
int __attribute__((noinline)) __vx_num_warps_wrapper(void) { return vx_num_warps(); }
void __attribute__((noinline)) __vx_barrier_wrapper(int id, int count) { vx_barrier(id, count); }

// Aliases to match the symbols generated by vortex-lower-runtime-builtins
__asm__(".global vx_core_id\n  vx_core_id = __vx_core_id_wrapper");
__asm__(".global vx_warp_id\n  vx_warp_id = __vx_warp_id_wrapper");
__asm__(".global vx_thread_id\n  vx_thread_id = __vx_thread_id_wrapper");
__asm__(".global vx_num_warps\n  vx_num_warps = __vx_num_warps_wrapper");
__asm__(".global vx_barrier\n  vx_barrier = __vx_barrier_wrapper");
